/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* JNI header for class org_jetbrains_kni_indexer_IndexerNative */

#ifndef _Included_org_jetbrains_kni_indexer_IndexerNative
#define _Included_org_jetbrains_kni_indexer_IndexerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jetbrains_kni_indexer_IndexerNative
 * Method:    buildNativeIndex
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jetbrains_kni_indexer_IndexerNative_buildNativeIndex
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}

std::string *doIndex(const std::vector<std::string>& args);

#endif
#endif
