/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kni_objc_Native */

#ifndef _Included_kni_objc_Native
#define _Included_kni_objc_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kni_objc_Native
 * Method:    dlopen
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_kni_objc_Native_dlopen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     kni_objc_Native
 * Method:    malloc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_kni_objc_Native_malloc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     kni_objc_Native
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_kni_objc_Native_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     kni_objc_Native
 * Method:    getWord
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_kni_objc_Native_getWord
  (JNIEnv *, jclass, jlong);

/*
 * Class:     kni_objc_Native
 * Method:    setWord
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_kni_objc_Native_setWord
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     kni_objc_Native
 * Method:    objc_getClass
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_kni_objc_Native_objc_1getClass
  (JNIEnv *, jclass, jstring);

/*
 * Class:     kni_objc_Native
 * Method:    objc_msgSend
 * Signature: (Ljava/lang/String;Lkni/objc/IObjCObject;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_kni_objc_Native_objc_1msgSend
  (JNIEnv *, jclass, jstring, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
