#!/bin/bash

# TODO: write a proper Makefile or build.xml

set -e

CWD=`dirname $0`
PROJECT=$CWD/../..
RUNTIME_OBJC=$PROJECT/out/production/runtime-objc

# TODO: do not depend on out/ here
[ ! -f $RUNTIME_OBJC/kni/objc/Native.class ] && echo "Native.class not found. Launch IDEA Make before building libKNIObjCRuntime" && exit 1

javah -classpath $RUNTIME_OBJC:$PROJECT/dependencies/kotlinc/lib/kotlin-runtime.jar -o $CWD/kniobjc.h kni.objc.Native

JAVA_HOME=`/usr/libexec/java_home`
JAVA_INCLUDE="-I$JAVA_HOME/include -I$JAVA_HOME/include/darwin"

mkdir $CWD/out
# TODO: statically link libffi instead of using path to library here
c++ -O2 -Wall -Wl,-no_compact_unwind $JAVA_INCLUDE -I$PROJECT/dependencies/libffi -L$PROJECT/dependencies/libffi -lffi -lobjc -dynamiclib $CWD/kniobjc.cc -o $CWD/out/libKNIObjCRuntime.dylib
